#pragma once
#include "CObj.h"
#include "CCollisionEvent.h"
#include "CMouseEvent.h"
#include "CObjPlayer2Grab.h"
#include "CObjMonster.h"

class CObjPlayer2 :
    public CObj, public CCollisionEvent, public CMousePosEvent, public CMouseKeyEvent
{
public:
	CObjPlayer2();
	virtual ~CObjPlayer2();

public:
	void Initialize() override;
	int Update() override;
	void Late_Update() override;
	void Render(HDC hDC) override;
	void Release() override;

public:
	void On_Collision(CObj* pObj, COLLISIONID eCollID, void* = nullptr) override;

public:
	void On_Mouse_Pos(CObj* pMouse) override;

public:
	void On_Mouse_Key_Down(CObj* pMouse) override;
	void On_Mouse_Key_Up(CObj* pMouse) override;
	void On_Mouse_Key_Pressing(CObj* pMouse) override;


public:
	void Grab(CObjPlayer2Grab* pObj);
	void ExcGrab(CObjPlayer2Grab* pObj, CObjMonster* pTarget);
	void Damage();

private:
	void DeltaUpdate();
	void Key_Input();
	void Apply_Gravity();
	void Apply_Jump();

	void JumpRoutine(float fAngle, float fSpeed);

	void Apply_Pend();
	void Move(float fAngle, float fLength);
	void Offset();

	void GrabLoad();
	void ExcGrabLoad();

	void ExcStart();

	void GrabHookResize();
private:
	DWORD m_dwTime;

	bool m_bGravity;
	float m_fGravityDeltaSum;
	
	bool m_bJump;
	float m_fJumpDeltaSum;
	float m_fJumpVelocity;
	float m_fJumpAngle;

	INFO m_tBeforeInfo;

	bool m_bFall;
	bool m_bGround;

	bool m_bLeftWallClimb;
	bool m_bRightWallClimb;
	bool m_bWallTopEscape;
	bool m_bWallDownEscape;
	bool m_bWallLeftEscape;
	bool m_bWallRightEscape;



	bool m_bExc;
	bool m_bExcGrabLoad;

	bool m_bCeilStick;
	INFO m_tCeilStickCollisionRectInfo;

	DIRECTION m_eLastLRDir;
	

	bool m_bGrabbing;
	bool m_bGrabLoad;
	bool m_bGrabHookResize;
	float m_fGrabHookResizeTargetX;
	float m_fGrabHookResizeTargetY;


	LINE m_tHookLine;
	float m_fHookGuideLength;
	float m_fHookMaxLength;
	float m_fHookMinLength;
	float m_fHookRadian;
	CObjPlayer2Grab* m_pGrab;


	float m_fPendLength;
	float m_fPendRad;
	float m_fPendCurr;
	float m_fPendDeltaSum;
	float m_fPendStartX;
	float m_fPendStartY;

	bool m_bDamaged;
	int m_iDamagedCnt;

	int m_iDamagedDashCnt;

	int m_iExcDashCnt;

	bool m_bDash;
	float m_fDashAngle;
	int m_iDashFrameCnt;

public:
	enum STATE
	{
		IDLE,
		MOVE,
		JUMP,
		WALL,
		CEILING_STICK,
		
		GRAP
	};
	STATE m_eState;


	enum ANI_STATE_SNB
	{
		AST_RIGHT_SNB_IDLE_START,
		AST_RIGHT_SNB_IDLE_ING,
		AST_RIGHT_SNB_IDLE_END,
		AST_LEFT_SNB_IDLE_START,
		AST_LEFT_SNB_IDLE_ING,
		AST_LEFT_SNB_IDLE_END,

		AST_RIGHT_SNB_RUNSTART_START,
		AST_RIGHT_SNB_RUNSTART_ING,
		AST_RIGHT_SNB_RUNSTART_END,
		AST_LEFT_SNB_RUNSTART_START,
		AST_LEFT_SNB_RUNSTART_ING,
		AST_LEFT_SNB_RUNSTART_END,

		AST_RIGHT_SNB_RUNNING_START,
		AST_RIGHT_SNB_RUNNING_ING,
		AST_RIGHT_SNB_RUNNING_END,
		AST_LEFT_SNB_RUNNING_START,
		AST_LEFT_SNB_RUNNING_ING,
		AST_LEFT_SNB_RUNNING_END,

		AST_RIGHT_SNB_RUNSTOP_START,
		AST_RIGHT_SNB_RUNSTOP_ING,
		AST_RIGHT_SNB_RUNSTOP_END,
		AST_LEFT_SNB_RUNSTOP_START,
		AST_LEFT_SNB_RUNSTOP_ING,
		AST_LEFT_SNB_RUNSTOP_END,

		AST_RIGHT_SNB_JUMPING_START,
		AST_RIGHT_SNB_JUMPING_ING,
		AST_RIGHT_SNB_JUMPING_END,
		AST_LEFT_SNB_JUMPING_START,
		AST_LEFT_SNB_JUMPING_ING,
		AST_LEFT_SNB_JUMPING_END,

		AST_RIGHT_SNB_FALLSTART_START,
		AST_RIGHT_SNB_FALLSTART_ING,
		AST_RIGHT_SNB_FALLSTART_END,
		AST_LEFT_SNB_FALLSTART_START,
		AST_LEFT_SNB_FALLSTART_ING,
		AST_LEFT_SNB_FALLSTART_END,

		AST_RIGHT_SNB_FALLING_START,
		AST_RIGHT_SNB_FALLING_ING,
		AST_RIGHT_SNB_FALLING_END,
		AST_LEFT_SNB_FALLING_START,
		AST_LEFT_SNB_FALLING_ING,
		AST_LEFT_SNB_FALLING_END,

		AST_RIGHT_SNB_LANDING_START,
		AST_RIGHT_SNB_LANDING_ING,
		AST_RIGHT_SNB_LANDING_END,
		AST_LEFT_SNB_LANDING_START,
		AST_LEFT_SNB_LANDING_ING,
		AST_LEFT_SNB_LANDING_END,

		AST_RIGHT_SNB_LAND2RUN_START,
		AST_RIGHT_SNB_LAND2RUN_ING,
		AST_RIGHT_SNB_LAND2RUN_END,
		AST_LEFT_SNB_LAND2RUN_START,
		AST_LEFT_SNB_LAND2RUN_ING,
		AST_LEFT_SNB_LAND2RUN_END,

		AST_RIGHT_SNB_WALL_SLIDE_START_START,
		AST_RIGHT_SNB_WALL_SLIDE_START_ING,
		AST_RIGHT_SNB_WALL_SLIDE_START_END,
		AST_LEFT_SNB_WALL_SLIDE_START_START,
		AST_LEFT_SNB_WALL_SLIDE_START_ING,
		AST_LEFT_SNB_WALL_SLIDE_START_END,


		AST_RIGHT_SNB_WALL_SLIDING_START,
		AST_RIGHT_SNB_WALL_SLIDING_ING,
		AST_RIGHT_SNB_WALL_SLIDING_END,
		AST_LEFT_SNB_WALL_SLIDING_START,
		AST_LEFT_SNB_WALL_SLIDING_ING,
		AST_LEFT_SNB_WALL_SLIDING_END,

		AST_RIGHT_SNB_WALL_CLIMBUP_START,
		AST_RIGHT_SNB_WALL_CLIMBUP_ING,
		AST_RIGHT_SNB_WALL_CLIMBUP_END,
		AST_LEFT_SNB_WALL_CLIMBUP_START,
		AST_LEFT_SNB_WALL_CLIMBUP_ING,
		AST_LEFT_SNB_WALL_CLIMBUP_END,

		AST_RIGHT_SNB_WALL_CLIMBDOWN_START,
		AST_RIGHT_SNB_WALL_CLIMBDOWN_ING,
		AST_RIGHT_SNB_WALL_CLIMBDOWN_END,
		AST_LEFT_SNB_WALL_CLIMBDOWN_START,
		AST_LEFT_SNB_WALL_CLIMBDOWN_ING,
		AST_LEFT_SNB_WALL_CLIMBDOWN_END,

		AST_RIGHT_SNB_SWING_START,
		AST_RIGHT_SNB_SWING_ING,
		AST_RIGHT_SNB_SWING_END,
		AST_LEFT_SNB_SWING_START,
		AST_LEFT_SNB_SWING_ING,
		AST_LEFT_SNB_SWING_END,

		AST_RIGHT_SNB_SWINGJUMP_START,
		AST_RIGHT_SNB_SWINGJUMP_ING,
		AST_RIGHT_SNB_SWINGJUMP_END,
		AST_LEFT_SNB_SWINGJUMP_START,
		AST_LEFT_SNB_SWINGJUMP_ING,
		AST_LEFT_SNB_SWINGJUMP_END,

		AST_RIGHT_SNB_SWINGJUMPUP_START,
		AST_RIGHT_SNB_SWINGJUMPUP_ING,
		AST_RIGHT_SNB_SWINGJUMPUP_END,
		AST_LEFT_SNB_SWINGJUMPUP_START,
		AST_LEFT_SNB_SWINGJUMPUP_ING,
		AST_LEFT_SNB_SWINGJUMPUP_END,


		AST_RIGHT_SNB_CEILINGSTICKSTART_START,
		AST_RIGHT_SNB_CEILINGSTICKSTART_ING,
		AST_RIGHT_SNB_CEILINGSTICKSTART_END,
		AST_LEFT_SNB_CEILINGSTICKSTART_START,
		AST_LEFT_SNB_CEILINGSTICKSTART_ING,
		AST_LEFT_SNB_CEILINGSTICKSTART_END,

		AST_RIGHT_SNB_CEILINGSTICKIDLE_START,
		AST_RIGHT_SNB_CEILINGSTICKIDLE_ING,
		AST_RIGHT_SNB_CEILINGSTICKIDLE_END,
		AST_LEFT_SNB_CEILINGSTICKIDLE_START,
		AST_LEFT_SNB_CEILINGSTICKIDLE_ING,
		AST_LEFT_SNB_CEILINGSTICKIDLE_END,

		AST_RIGHT_SNB_CEILINGSTICKJUMP_START,
		AST_RIGHT_SNB_CEILINGSTICKJUMP_ING,
		AST_RIGHT_SNB_CEILINGSTICKJUMP_END,
		AST_LEFT_SNB_CEILINGSTICKJUMP_START,
		AST_LEFT_SNB_CEILINGSTICKJUMP_ING,
		AST_LEFT_SNB_CEILINGSTICKJUMP_END,

		AST_RIGHT_SNB_DAMAGED_START,
		AST_RIGHT_SNB_DAMAGED_ING,
		AST_RIGHT_SNB_DAMAGED_END,
		AST_LEFT_SNB_DAMAGED_START,
		AST_LEFT_SNB_DAMAGED_ING,
		AST_LEFT_SNB_DAMAGED_END,

		AST_RIGHT_SNB_DASH_START,
		AST_RIGHT_SNB_DASH_ING,
		AST_RIGHT_SNB_DASH_END,
		AST_LEFT_SNB_DASH_START,
		AST_LEFT_SNB_DASH_ING,
		AST_LEFT_SNB_DASH_END,


		AST_RIGHT_SNB_EXCWINDING_START,
		AST_RIGHT_SNB_EXCWINDING_ING,
		AST_RIGHT_SNB_EXCWINDING_END,
		AST_LEFT_SNB_EXCWINDING_START,
		AST_LEFT_SNB_EXCWINDING_ING,
		AST_LEFT_SNB_EXCWINDING_END,


		AST_RIGHT_SNB_EXCHOLDBACK_START,
		AST_RIGHT_SNB_EXCHOLDBACK_ING,
		AST_RIGHT_SNB_EXCHOLDBACK_END,
		AST_LEFT_SNB_EXCHOLDBACK_START,
		AST_LEFT_SNB_EXCHOLDBACK_ING,
		AST_LEFT_SNB_EXCHOLDBACK_END,

		AST_RIGHT_SNB_EXCDASH_START,
		AST_RIGHT_SNB_EXCDASH_ING,
		AST_RIGHT_SNB_EXCDASH_END,
		AST_LEFT_SNB_EXCDASH_START,
		AST_LEFT_SNB_EXCDASH_ING,
		AST_LEFT_SNB_EXCDASH_END,
	};
	ANI_STATE_SNB m_eAniStateSNB;

	enum ANI_STATE_SNBARM
	{
		AST_RIGHT_ARM_IDLE_START,
		AST_RIGHT_ARM_IDLE_ING,
		AST_RIGHT_ARM_IDLE_END,
		AST_LEFT_ARM_IDLE_START,
		AST_LEFT_ARM_IDLE_ING,
		AST_LEFT_ARM_IDLE_END,

		AST_RIGHT_ARM_RUNSTART_START,
		AST_RIGHT_ARM_RUNSTART_ING,
		AST_RIGHT_ARM_RUNSTART_END,
		AST_LEFT_ARM_RUNSTART_START,
		AST_LEFT_ARM_RUNSTART_ING,
		AST_LEFT_ARM_RUNSTART_END,

		AST_RIGHT_ARM_RUNNING_START,
		AST_RIGHT_ARM_RUNNING_ING,
		AST_RIGHT_ARM_RUNNING_END,
		AST_LEFT_ARM_RUNNING_START,
		AST_LEFT_ARM_RUNNING_ING,
		AST_LEFT_ARM_RUNNING_END,

		AST_RIGHT_ARM_RUNSTOP_START,
		AST_RIGHT_ARM_RUNSTOP_ING,
		AST_RIGHT_ARM_RUNSTOP_END,
		AST_LEFT_ARM_RUNSTOP_START,
		AST_LEFT_ARM_RUNSTOP_ING,
		AST_LEFT_ARM_RUNSTOP_END,

		AST_RIGHT_ARM_JUMPING_START,
		AST_RIGHT_ARM_JUMPING_ING,
		AST_RIGHT_ARM_JUMPING_END,
		AST_LEFT_ARM_JUMPING_START,
		AST_LEFT_ARM_JUMPING_ING,
		AST_LEFT_ARM_JUMPING_END,

		AST_RIGHT_ARM_FALLSTART_START,
		AST_RIGHT_ARM_FALLSTART_ING,
		AST_RIGHT_ARM_FALLSTART_END,
		AST_LEFT_ARM_FALLSTART_START,
		AST_LEFT_ARM_FALLSTART_ING,
		AST_LEFT_ARM_FALLSTART_END,

		AST_RIGHT_ARM_FALLING_START,
		AST_RIGHT_ARM_FALLING_ING,
		AST_RIGHT_ARM_FALLING_END,
		AST_LEFT_ARM_FALLING_START,
		AST_LEFT_ARM_FALLING_ING,
		AST_LEFT_ARM_FALLING_END,

		AST_RIGHT_ARM_LANDING_START,
		AST_RIGHT_ARM_LANDING_ING,
		AST_RIGHT_ARM_LANDING_END,
		AST_LEFT_ARM_LANDING_START,
		AST_LEFT_ARM_LANDING_ING,
		AST_LEFT_ARM_LANDING_END,

		AST_RIGHT_ARM_LAND2RUN_START,
		AST_RIGHT_ARM_LAND2RUN_ING,
		AST_RIGHT_ARM_LAND2RUN_END,
		AST_LEFT_ARM_LAND2RUN_START,
		AST_LEFT_ARM_LAND2RUN_ING,
		AST_LEFT_ARM_LAND2RUN_END,

		AST_RIGHT_ARM_WALL_SLIDE_START_START,
		AST_RIGHT_ARM_WALL_SLIDE_START_ING,
		AST_RIGHT_ARM_WALL_SLIDE_START_END,
		AST_LEFT_ARM_WALL_SLIDE_START_START,
		AST_LEFT_ARM_WALL_SLIDE_START_ING,
		AST_LEFT_ARM_WALL_SLIDE_START_END,


		AST_RIGHT_ARM_WALL_SLIDING_START,
		AST_RIGHT_ARM_WALL_SLIDING_ING,
		AST_RIGHT_ARM_WALL_SLIDING_END,
		AST_LEFT_ARM_WALL_SLIDING_START,
		AST_LEFT_ARM_WALL_SLIDING_ING,
		AST_LEFT_ARM_WALL_SLIDING_END,

		AST_RIGHT_ARM_WALL_CLIMBUP_START,
		AST_RIGHT_ARM_WALL_CLIMBUP_ING,
		AST_RIGHT_ARM_WALL_CLIMBUP_END,
		AST_LEFT_ARM_WALL_CLIMBUP_START,
		AST_LEFT_ARM_WALL_CLIMBUP_ING,
		AST_LEFT_ARM_WALL_CLIMBUP_END,

		AST_RIGHT_ARM_WALL_CLIMBDOWN_START,
		AST_RIGHT_ARM_WALL_CLIMBDOWN_ING,
		AST_RIGHT_ARM_WALL_CLIMBDOWN_END,
		AST_LEFT_ARM_WALL_CLIMBDOWN_START,
		AST_LEFT_ARM_WALL_CLIMBDOWN_ING,
		AST_LEFT_ARM_WALL_CLIMBDOWN_END,

		AST_RIGHT_ARM_SWING_START,
		AST_RIGHT_ARM_SWING_ING,
		AST_RIGHT_ARM_SWING_END,
		AST_LEFT_ARM_SWING_START,
		AST_LEFT_ARM_SWING_ING,
		AST_LEFT_ARM_SWING_END,

		AST_RIGHT_ARM_SWINGJUMP_START,
		AST_RIGHT_ARM_SWINGJUMP_ING,
		AST_RIGHT_ARM_SWINGJUMP_END,
		AST_LEFT_ARM_SWINGJUMP_START,
		AST_LEFT_ARM_SWINGJUMP_ING,
		AST_LEFT_ARM_SWINGJUMP_END,

		AST_RIGHT_ARM_SWINGJUMPUP_START,
		AST_RIGHT_ARM_SWINGJUMPUP_ING,
		AST_RIGHT_ARM_SWINGJUMPUP_END,
		AST_LEFT_ARM_SWINGJUMPUP_START,
		AST_LEFT_ARM_SWINGJUMPUP_ING,
		AST_LEFT_ARM_SWINGJUMPUP_END,


		AST_RIGHT_ARM_CEILINGSTICKSTART_START,
		AST_RIGHT_ARM_CEILINGSTICKSTART_ING,
		AST_RIGHT_ARM_CEILINGSTICKSTART_END,
		AST_LEFT_ARM_CEILINGSTICKSTART_START,
		AST_LEFT_ARM_CEILINGSTICKSTART_ING,
		AST_LEFT_ARM_CEILINGSTICKSTART_END,

		AST_RIGHT_ARM_CEILINGSTICKIDLE_START,
		AST_RIGHT_ARM_CEILINGSTICKIDLE_ING,
		AST_RIGHT_ARM_CEILINGSTICKIDLE_END,
		AST_LEFT_ARM_CEILINGSTICKIDLE_START,
		AST_LEFT_ARM_CEILINGSTICKIDLE_ING,
		AST_LEFT_ARM_CEILINGSTICKIDLE_END,

		AST_RIGHT_ARM_CEILINGSTICKJUMP_START,
		AST_RIGHT_ARM_CEILINGSTICKJUMP_ING,
		AST_RIGHT_ARM_CEILINGSTICKJUMP_END,
		AST_LEFT_ARM_CEILINGSTICKJUMP_START,
		AST_LEFT_ARM_CEILINGSTICKJUMP_ING,
		AST_LEFT_ARM_CEILINGSTICKJUMP_END,


		AST_RIGHT_ARM_CEILINGSTICKMOVESTART_START,
		AST_RIGHT_ARM_CEILINGSTICKMOVESTART_ING,
		AST_RIGHT_ARM_CEILINGSTICKMOVESTART_END,
		AST_LEFT_ARM_CEILINGSTICKMOVESTART_START,
		AST_LEFT_ARM_CEILINGSTICKMOVESTART_ING,
		AST_LEFT_ARM_CEILINGSTICKMOVESTART_END,

		AST_RIGHT_ARM_CEILINGSTICKMOVING_START,
		AST_RIGHT_ARM_CEILINGSTICKMOVING_ING,
		AST_RIGHT_ARM_CEILINGSTICKMOVING_END,
		AST_LEFT_ARM_CEILINGSTICKMOVING_START,
		AST_LEFT_ARM_CEILINGSTICKMOVING_ING,
		AST_LEFT_ARM_CEILINGSTICKMOVING_END,

		AST_RIGHT_ARM_CEILINGSTICKMOVEEND_START,
		AST_RIGHT_ARM_CEILINGSTICKMOVEEND_ING,
		AST_RIGHT_ARM_CEILINGSTICKMOVEEND_END,
		AST_LEFT_ARM_CEILINGSTICKMOVEEND_START,
		AST_LEFT_ARM_CEILINGSTICKMOVEEND_ING,
		AST_LEFT_ARM_CEILINGSTICKMOVEEND_END,


		AST_RIGHT_ARM_DAMAGED_START,
		AST_RIGHT_ARM_DAMAGED_ING,
		AST_RIGHT_ARM_DAMAGED_END,
		AST_LEFT_ARM_DAMAGED_START,
		AST_LEFT_ARM_DAMAGED_ING,
		AST_LEFT_ARM_DAMAGED_END,

		AST_RIGHT_ARM_DASH_START,
		AST_RIGHT_ARM_DASH_ING,
		AST_RIGHT_ARM_DASH_END,
		AST_LEFT_ARM_DASH_START,
		AST_LEFT_ARM_DASH_ING,
		AST_LEFT_ARM_DASH_END,


		AST_RIGHT_ARM_EXCHOLDBACK_START,
		AST_RIGHT_ARM_EXCHOLDBACK_ING,
		AST_RIGHT_ARM_EXCHOLDBACK_END,
		AST_LEFT_ARM_EXCHOLDBACK_START,
		AST_LEFT_ARM_EXCHOLDBACK_ING,
		AST_LEFT_ARM_EXCHOLDBACK_END,

		AST_RIGHT_ARM_EXCDASH_START,
		AST_RIGHT_ARM_EXCDASH_ING,
		AST_RIGHT_ARM_EXCDASH_END,
		AST_LEFT_ARM_EXCDASH_START,
		AST_LEFT_ARM_EXCDASH_ING,
		AST_LEFT_ARM_EXCDASH_END,
	};
	ANI_STATE_SNBARM m_eAniStateSNBARM;

	int m_iSound;

	DWORD m_dwFootStepSoundTime;
	DWORD m_dwWallClimbUpSoundTime;
	DWORD m_dwCeilingMoveSoundTime;
};

