#pragma once
#include "CObjMonster.h"
#include "CCollisionEvent.h"
class CObjMonsterWarrior :
    public CObjMonster, public CCollisionEvent
{
public:
	CObjMonsterWarrior();
	virtual ~CObjMonsterWarrior();

public:
	void Initialize() override;
	int Update() override;
	void Late_Update() override;
	void Render(HDC hDC) override;
	void Release() override;

public:
	void On_Collision(CObj* pObj, COLLISIONID eCollID, void* = nullptr) override;

public:
	void Excuted(CObj* pPlayer, float fRad) override;
	void Grabbed(CObj* pPlayer) override;
private:
	void Motion_Change();

private:
	FRAME_STATE_ID m_ePreState;
	FRAME_STATE_ID m_eCurState;


private:
	void DeltaUpdate();

private:
	DWORD m_dwTime;
	float m_fLemnisDeltaSum;

	bool m_bOriginSet;
	float m_fOriginX;
	float m_fOriginY;

	bool m_bTracing;
	bool m_bHovering;

public:
	enum ANI_STATE
	{
		AST_RIGHT_SPAWN_START,
		AST_RIGHT_SPAWN_ING,
		AST_RIGHT_SPAWN_END,


		AST_LEFT_SPAWN_START,
		AST_LEFT_SPAWN_ING,
		AST_LEFT_SPAWN_END,

		AST_RIGHT_IDLE_START,
		AST_RIGHT_IDLE_ING,
		AST_RIGHT_IDLE_END,

		AST_LEFT_IDLE_START,
		AST_LEFT_IDLE_ING,
		AST_LEFT_IDLE_END,

		AST_RIGHT_DEAD_START,
		AST_RIGHT_DEAD_ING,
		AST_RIGHT_DEAD_END,

		AST_LEFT_DEAD_START,
		AST_LEFT_DEAD_ING,
		AST_LEFT_DEAD_END,

		AST_RIGHT_EXCHOLDSTART_START,
		AST_RIGHT_EXCHOLDSTART_ING,
		AST_RIGHT_EXCHOLDSTART_END,


		AST_LEFT_EXCHOLDSTART_START,
		AST_LEFT_EXCHOLDSTART_ING,
		AST_LEFT_EXCHOLDSTART_END,

		AST_RIGHT_EXCHOLDBACK_START,
		AST_RIGHT_EXCHOLDBACK_ING,
		AST_RIGHT_EXCHOLDBACK_END,


		AST_LEFT_EXCHOLDBACK_START,
		AST_LEFT_EXCHOLDBACK_ING,
		AST_LEFT_EXCHOLDBACK_END,

		AST_RIGHT_COMASTART_START,
		AST_RIGHT_COMASTART_ING,
		AST_RIGHT_COMASTART_END,

		AST_LEFT_COMASTART_START,
		AST_LEFT_COMASTART_ING,
		AST_LEFT_COMASTART_END,

		AST_RIGHT_COMALOOP_START,
		AST_RIGHT_COMALOOP_ING,
		AST_RIGHT_COMALOOP_END,

		AST_LEFT_COMALOOP_START,
		AST_LEFT_COMALOOP_ING,
		AST_LEFT_COMALOOP_END,

		AST_RIGHT_COMAEND_START,
		AST_RIGHT_COMAEND_ING,
		AST_RIGHT_COMAEND_END,

		AST_LEFT_COMAEND_START,
		AST_LEFT_COMAEND_ING,
		AST_LEFT_COMAEND_END,

		AST_RIGHT_MOVESTART_START,
		AST_RIGHT_MOVESTART_ING,
		AST_RIGHT_MOVESTART_END,

		AST_RIGHT_MOVING_START,
		AST_RIGHT_MOVING_ING,
		AST_RIGHT_MOVING_END,

		AST_RIGHT_MOVEEND_START,
		AST_RIGHT_MOVEEND_ING,
		AST_RIGHT_MOVEEND_END,

		AST_RIGHT_ATTACKREADY_START,
		AST_RIGHT_ATTACKREADY_ING,
		AST_RIGHT_ATTACKREADY_END,

		AST_RIGHT_ATTACKEND_START,
		AST_RIGHT_ATTACKEND_ING,
		AST_RIGHT_ATTACKEND_END,

		AST_RIGHT_ATTACK_START,
		AST_RIGHT_ATTACK_ING,
		AST_RIGHT_ATTACK_END,

		AST_LEFT_MOVESTART_START,
		AST_LEFT_MOVESTART_ING,
		AST_LEFT_MOVESTART_END,

		AST_LEFT_MOVING_START,
		AST_LEFT_MOVING_ING,
		AST_LEFT_MOVING_END,

		AST_LEFT_MOVEEND_START,
		AST_LEFT_MOVEEND_ING,
		AST_LEFT_MOVEEND_END,

		AST_LEFT_ATTACKREADY_START,
		AST_LEFT_ATTACKREADY_ING,
		AST_LEFT_ATTACKREADY_END,

		AST_LEFT_ATTACKEND_START,
		AST_LEFT_ATTACKEND_ING,
		AST_LEFT_ATTACKEND_END,

		AST_LEFT_ATTACK_START,
		AST_LEFT_ATTACK_ING,
		AST_LEFT_ATTACK_END,
		
	};
	ANI_STATE m_eAniState;
};

